fixes

diff --git a/git-grlp b/git-grlp
--- a/git-grlp
+++ b/git-grlp
@@ -1,6 +1,16 @@
 #!/bin/sh
 
-# This script merges the updated develop to the current branch
+# Fetch the latest changes from origin
 git fetch
+
+# Attempt to merge origin/develop into the current branch
 git merge origin/develop
-git push
+merge_exit_code=$?
+
+if [ $merge_exit_code -ne 0 ]; then
+    # A non-zero exit code likely means merge conflicts occurred
+    echo "Please resolve the conflicts, commit, and push when ready."
+else
+    # No conflicts, safe to push
+    git push
+fi
